from __future__ import annotations

from dataclasses import dataclass, field
from hashlib import sha256
from pathlib import Path
import json
from typing import Any

from .classify import ComparisonClassification, FindingCause
from .cases import ToyCase


def _json_dump(payload: Any) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


@dataclass(frozen=True, slots=True)
class AuditObservationSummary:
    case_id: str
    event_sequence: tuple[str, ...]
    terminal_status: str | None
    reward_timing: str | None
    notes: str = ""

    def to_dict(self) -> dict[str, object]:
        return {
            "case_id": self.case_id,
            "event_sequence": list(self.event_sequence),
            "terminal_status": self.terminal_status,
            "reward_timing": self.reward_timing,
            "notes": self.notes,
        }


@dataclass(frozen=True, slots=True)
class ComparisonResult:
    case_id: str
    classification: ComparisonClassification
    finding_cause: FindingCause
    reference_summary: AuditObservationSummary
    environment_summary: AuditObservationSummary
    notes: str = ""

    def to_dict(self) -> dict[str, object]:
        return {
            "case_id": self.case_id,
            "classification": self.classification.value,
            "finding_cause": self.finding_cause.value,
            "reference_summary": self.reference_summary.to_dict(),
            "environment_summary": self.environment_summary.to_dict(),
            "notes": self.notes,
        }


@dataclass(frozen=True, slots=True)
class Finding:
    finding_id: str
    case_id: str
    classification: ComparisonClassification
    cause: FindingCause
    evidence: str
    notes: str = ""

    def to_dict(self) -> dict[str, object]:
        return {
            "finding_id": self.finding_id,
            "case_id": self.case_id,
            "classification": self.classification.value,
            "cause": self.cause.value,
            "evidence": self.evidence,
            "notes": self.notes,
        }


@dataclass(slots=True)
class AuditReport:
    metadata: dict[str, object]
    toy_cases: list[dict[str, object]]
    reference_summary: list[dict[str, object]]
    environment_summary: list[dict[str, object]]
    comparison_results: list[dict[str, object]]
    findings: list[dict[str, object]]
    assumptions: list[dict[str, object]]
    instrumentation_gaps: list[dict[str, object]]
    unsupported_cases: list[dict[str, object]]
    no_fix_disclaimer: str
    reproducibility: dict[str, object]
    overall_status: str

    def to_dict(self) -> dict[str, object]:
        return {
            "metadata": dict(self.metadata),
            "toy_cases": list(self.toy_cases),
            "reference_summary": list(self.reference_summary),
            "environment_summary": list(self.environment_summary),
            "comparison_results": list(self.comparison_results),
            "findings": list(self.findings),
            "assumptions": list(self.assumptions),
            "instrumentation_gaps": list(self.instrumentation_gaps),
            "unsupported_cases": list(self.unsupported_cases),
            "no_fix_disclaimer": self.no_fix_disclaimer,
            "reproducibility": dict(self.reproducibility),
            "overall_status": self.overall_status,
        }

    def to_json(self) -> str:
        return _json_dump(self.to_dict())

    def to_markdown(self) -> str:
        lines = [
            "# Differential Environment Audit",
            "",
            "## Metadata",
            f"- Feature: `{self.metadata.get('feature_id', '')}`",
            f"- Generated by: `{self.metadata.get('generated_by', '')}`",
            f"- Deterministic: `{self.metadata.get('deterministic', False)}`",
            "",
            "## Toy Cases",
        ]
        for case in self.toy_cases:
            lines.append(f"- `{case['case_id']}`: {case['scenario_type']} -> action `{case['action']}`")
        lines.extend([
            "",
            "## Reference Ledger Summary",
        ])
        for item in self.reference_summary:
            lines.append(f"- `{item['case_id']}`: {', '.join(item['event_sequence'])}")
        lines.extend([
            "",
            "## Environment Observed Lifecycle Summary",
        ])
        for item in self.environment_summary:
            lines.append(f"- `{item['case_id']}`: {', '.join(item['event_sequence']) or 'unsupported'}")
        lines.extend([
            "",
            "## Comparison Results",
        ])
        for item in self.comparison_results:
            lines.append(f"- `{item['case_id']}`: {item['classification']} / {item['finding_cause']}")
        lines.extend([
            "",
            "## Findings",
        ])
        for item in self.findings:
            lines.append(f"- `{item['finding_id']}` `{item['case_id']}`: {item['classification']} / {item['cause']}")
        lines.extend([
            "",
            "## Assumptions",
        ])
        for item in self.assumptions:
            lines.append(f"- `{item['case_id']}`: {item['text']}")
        lines.extend([
            "",
            "## Instrumentation Gaps",
        ])
        for item in self.instrumentation_gaps:
            lines.append(f"- `{item['case_id']}`: {item['text']}")
        lines.extend([
            "",
            "## Unsupported Cases",
        ])
        for item in self.unsupported_cases:
            lines.append(f"- `{item['case_id']}`: {item['text']}")
        lines.extend([
            "",
            "## No-Fix Disclaimer",
            self.no_fix_disclaimer,
            "",
            "## Reproducibility",
        ])
        for key, value in self.reproducibility.items():
            lines.append(f"- {key}: `{value}`")
        lines.extend([
            "",
            f"## Overall Status\n\n{self.overall_status}",
            "",
        ])
        return "\n".join(lines)

    def write(self, output_dir: Path) -> tuple[Path, Path]:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        json_path = output_dir / "differential-audit.json"
        md_path = output_dir / "differential-audit.md"
        json_path.write_text(self.to_json(), encoding="utf-8")
        md_path.write_text(self.to_markdown(), encoding="utf-8")
        return json_path, md_path


def stable_report_hash(payload: dict[str, object]) -> str:
    return sha256(_json_dump(payload).encode("utf-8")).hexdigest()


def summarize_sequence(items: list[dict[str, object]], key: str = "event_sequence") -> list[str]:
    return [", ".join(item.get(key, [])) for item in items]
